name: Build Mods Command
on:
  push:
    branches: [ '**' ]
  pull_request:
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout git repository"
        uses: actions/checkout@v3
      - name: "setup jdk"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: "gradle and caching setup"
        uses: jpenilla/actions/minecraft-gradle-setup@v0
        with:
          loom: true
      - name: "execute gradle build"
        run: ./gradlew build
      - name: "collect artifacts"
        run: mkdir staging && cp build/libs/mods-command-mc*.jar staging
      - name: "upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: Jars
          path: staging
